language: php

php:
    7.4

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - mysql -e 'CREATE DATABASE lanager;'

before_script:
    - composer self-update
    - composer install --no-interaction
    - cp .env.travis .env
    - php artisan key:generate
    - php artisan storage:link
    - php artisan serve > /dev/null 2>&1 &

script: vendor/bin/behat
